/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yinpsoft.struts.form;

import java.util.Date;
import java.util.List;

import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;

import org.apache.commons.validator.Validator;
import org.apache.commons.validator.ValidatorException;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.Resources;
import org.apache.struts.validator.ValidatorForm;

import com.yinpsoft.beans.Customertype;

/** 
 * MyEclipse Struts
 * Creation date: 01-12-2009
 * 
 * XDoclet definition:
 * @struts.form name="customerTypeForm"
 */
public class CustomerTypeForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	/** customerTypeName property */
	private String customerTypeName;

	/** customerTypeCode property */
	private String customerTypeCode;
	
	private String isvoid ;

	private Date created;
	
	private List<Customertype> customerTypes;
	
	private String[] customerTypeIds;
	
	private String delete;	
	
	private int totalPages = 0;
	
	public static int PAGE_SIZE = 20;
	
	private int currentPage = 1;

	/*
	 * Generated Methods
	 */

	
	public ActionErrors validate(ActionMapping mapping,
	        HttpServletRequest request) {
//	        ServletContext application = getServlet().getServletContext();
//	        ActionErrors errors = new ActionErrors();
//
//	        String validationKey = getValidationKey(mapping, request);
//
//	        Validator validator =
//	            Resources.initValidator(validationKey, this, application, request,
//	                errors, page);
//
//	        try {
//	            validatorResults = validator.validate();
//	        } catch (ValidatorException e) {
//	            log.error(e.getMessage(), e);
//	        }

	        return null;
	    }
	
	/**
	 * @return the isvoid
	 */
	public String getIsvoid() {
		return isvoid;
	}

	/**
	 * @param isvoid the isvoid to set
	 */
	public void setIsvoid(String isvoid) {
		this.isvoid = isvoid;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the customerTypeName.
	 * @return String
	 */
	public String getCustomerTypeName() {
		return customerTypeName;
	}

	/** 
	 * Set the customerTypeName.
	 * @param customerTypeName The customerTypeName to set
	 */
	public void setCustomerTypeName(String customerTypeName) {
		this.customerTypeName = customerTypeName;
	}

	/** 
	 * Returns the customerTypeCode.
	 * @return String
	 */
	public String getCustomerTypeCode() {
		return customerTypeCode;
	}

	/** 
	 * Set the customerTypeCode.
	 * @param customerTypeCode The customerTypeCode to set
	 */
	public void setCustomerTypeCode(String customerTypeCode) {
		this.customerTypeCode = customerTypeCode;
	}

	/**
	 * @param created the created to set
	 */
	public void setCreated(Date created) {
		this.created = created;
	}

	/**
	 * @return the created
	 */
	public String getCreated() {
		return created.toString();
	}

	/**
	 * @param customerTypes the customerTypes to set
	 */
	public void setCustomerTypes(List<Customertype> customerTypes) {
		this.customerTypes = customerTypes;
	}

	/**
	 * @return the customerTypes
	 */
	public List<Customertype> getCustomerTypes() {
		return customerTypes;
	}

	/**
	 * @param customerTypeIds the customerTypeIds to set
	 */
	public void setCustomerTypeIds(String[] customerTypeIds) {
		this.customerTypeIds = customerTypeIds;
	}

	/**
	 * @return the customerTypeIds
	 */
	public String[] getCustomerTypeIds() {
		return customerTypeIds;
	}

	/**
	 * @param delete the delete to set
	 */
	public void setDelete(String delete) {
		this.delete = delete;
	}

	/**
	 * @return the delete
	 */
	public String getDelete() {
		return delete;
	}

	/**
	 * @return the totalPages
	 */
	public int getTotalPages() {
		return totalPages;
	}

	/**
	 * @param totalPages the totalPages to set
	 */
	public void setTotalPages(int totalPages) {
		this.totalPages = totalPages;
	}

	/**
	 * @return the currentPage
	 */
	public int getCurrentPage() {
		return currentPage;
	}

	/**
	 * @param currentPage the currentPage to set
	 */
	public void setCurrentPage(int currentPage) {
		this.currentPage = currentPage;
	}
}