/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yinpsoft.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionRedirect;
import org.apache.struts.actions.DispatchAction;

import com.yinpsoft.BaseDAO;
import com.yinpsoft.beans.Customertype;
import com.yinpsoft.daos.CustomerTypeDAO;
import com.yinpsoft.struts.form.CustomerTypeForm;
import com.yinpsoft.struts.form.CustomerTypeListForm;
import com.yinpsoft.struts.form.CustomerTypeViewForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-14-2009
 * 
 * XDoclet definition:
 * @struts.action path="/customerTypeView" name="customerTypeViewForm" input="/views/customers/customerTypeView.jsp" scope="request" validate="true"
 */
public class CustomerTypeViewAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	private static Log logger = (Log) LogFactory.getLog(CustomerTypeViewAction.class);
	
	
//	public ActionForward list(ActionMapping mapping, ActionForm form,
//			HttpServletRequest request, HttpServletResponse response){
//		logger.debug(this.clazz.getName()+".list Begin...............................................");
//		
//		CustomerTypeListForm customerTypeListForm = (CustomerTypeListForm) form;
//		CustomerTypeDAO CustomerTypeDao = new CustomerTypeDAO();
//				
//		try {
//			List<Customertype> customerTypes = (List<Customertype>)CustomerTypeDao.findAll();
//			customerTypeListForm.setCustomerTypes(customerTypes);
//			BaseDAO.Commit();
//		} catch (Exception e){
//			BaseDAO.Rollback();
//		}
//		
//		logger.debug(this.clazz.getName()+".list End...............................................");
//		
//		return new ActionForward("/customerTypeList.do?action=list");//mapping.findForward("customerTypeList");
//	}
	
	public ActionForward edit(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		logger.debug(this.clazz.getName()+".edit Begin...............................................");
		
		String id = request.getParameter("customerTypeId");
//		CustomerTypeViewForm customerTypeForm = (CustomerTypeViewForm)form;
//		CustomerTypeDAO customerTypeDao = new CustomerTypeDAO();
////		ActionForward af = null;
//		Customertype customerType = null;
//		try{
//			customerType = customerTypeDao.findById(id);
//			customerTypeForm.setCustomerTypeCode(customerType.getCustomertypecode());
//			customerTypeForm.setCustomerTypeName(customerType.getCustomertypename());
//			
//			BaseDAO.Commit();
//			
////			af = new ActionForward("/customerType.do?action=edit&customerTypeId="+customerType.getCustomertypeid());
////			af.setRedirect(true);
////			af.setProperty("customertypecode", customerType.getCustomertypecode());
////			af.setProperty("customertypename", customerType.getCustomertypename());
//		} catch (Exception e){
//			BaseDAO.Rollback();
//		}
		logger.debug(this.clazz.getName()+".edit End...............................................");
				
		return new ActionForward("/customerType.do?action=edit&customerTypeId="+id);
	}
	
	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		logger.debug(this.clazz.getName()+".delete Begin...............................................");
		
		String id = request.getParameter("customerTypeId");
		CustomerTypeDAO customerTypeDao = new CustomerTypeDAO();
		try {
			customerTypeDao.delete(customerTypeDao.findById(id));
			BaseDAO.Commit();
		} catch (Exception e) {
			BaseDAO.Rollback();
		}
		
		logger.debug(this.clazz.getName()+".delete End...............................................");
		
		return new ActionForward("/customerTypeList.do?action=list");
	}
	
	public ActionForward view(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response){
		
		logger.debug(this.clazz.getName()+".view Begin...............................................");
		
		String id = request.getParameter("customerTypeId");
		CustomerTypeDAO customerTypeDao = new CustomerTypeDAO();
		CustomerTypeForm customerTypeForm = (CustomerTypeForm)form;
		
		try {
			Customertype customerType = customerTypeDao.findById(id);			
			customerTypeForm.setCustomerTypeName(customerType.getCustomertypename());
			customerTypeForm.setCustomerTypeCode(customerType.getCustomertypecode());
			
			BaseDAO.Commit();
		} catch (Exception e){
			BaseDAO.Rollback();
		}
		
		logger.debug(this.clazz.getName()+".view End...............................................");
		
		return mapping.findForward("customerTypeView");
	}
	
}